# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  event-consortium:

services:

  orderer.event-consortium.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.event-consortium.com
    container_name: orderer.event-consortium.com
    networks:
      - event-consortium

  peer0.centralbank.event-consortium.com:
    container_name: peer0.centralbank.event-consortium.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.centralbank.event-consortium.com
    networks:
      - event-consortium

  peer1.centralbank.event-consortium.com:
    container_name: peer1.centralbank.event-consortium.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.centralbank.event-consortium.com
    networks:
      - event-consortium

  peer0.org1.event-consortium.com:
    container_name: peer0.org1.event-consortium.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.event-consortium.com
    networks:
      - event-consortium

  peer1.org1.event-consortium.com:
    container_name: peer1.org1.event-consortium.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.event-consortium.com
    networks:
      - event-consortium

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.centralbank.event-consortium.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/centralbank.event-consortium.com/peers/peer0.centralbank.event-consortium.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/centralbank.event-consortium.com/peers/peer0.centralbank.event-consortium.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/centralbank.event-consortium.com/peers/peer0.centralbank.event-consortium.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/centralbank.event-consortium.com/users/Admin@centralbank.event-consortium.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME} ${DELAY} ${LANG}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.event-consortium.com
      - peer0.centralbank.event-consortium.com
      - peer1.centralbank.event-consortium.com
      - peer0.org1.event-consortium.com
      - peer1.org1.event-consortium.com
    networks:
      - event-consortium
