# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  event-consortium:
services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-centralbank
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.centralbank.event-consortium.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.centralbank.event-consortium.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/centralbank.event-consortium.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCentralBank
    networks:
      - event-consortium

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.event-consortium.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.event-consortium.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.event-consortium.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - event-consortium

  orderer.event-consortium.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.event-consortium.com
    container_name: orderer.event-consortium.com
    networks:
      - event-consortium

  peer0.centralbank.event-consortium.com:
    container_name: peer0.centralbank.event-consortium.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.centralbank.event-consortium.com
    networks:
      - event-consortium

  peer1.centralbank.event-consortium.com:
    container_name: peer1.centralbank.event-consortium.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.centralbank.event-consortium.com
    networks:
      - event-consortium

  peer0.org1.event-consortium.com:
    container_name: peer0.org1.event-consortium.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.event-consortium.com
    networks:
      - event-consortium

  peer1.org1.event-consortium.com:
    container_name: peer1.org1.event-consortium.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.event-consortium.com
    networks:
      - event-consortium
